# Generated by Django 5.0.6 on 2024-07-06 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='origins',
            new_name='origin',
        ),
    ]
